### ISSUE TITLE
Remove underline from links

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#10]
<img width="141" alt="image" src="https://github.com/joplin/website-plugin-discovery/assets/1285584/b950d8ca-7ec7-402d-a11f-f639ab9aeef0">

Also here:

<img width="448" alt="image" src="https://github.com/joplin/website-plugin-discovery/assets/1285584/484c25bb-4b00-47b7-96a4-2c9a6a819951">

It makes the page a bit too busy and I think it's already clear from the colour and positioning that those are links

**Comment by personalizedrefrigerator** [comment]
Fixed by 38a052b54dd819b869bdd28eb9fe474048f33a85
