### ISSUE TITLE
Use same font size as original design for titles and descriptions

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#11]
<img width="503" alt="image" src="https://github.com/joplin/website-plugin-discovery/assets/1285584/d77a4267-4c09-4f5d-aa4b-3abe4aac5441">

The original design uses a smaller font

**Comment by personalizedrefrigerator** [comment]
Addressed in https://github.com/joplin/website-plugin-discovery/commit/1e10b62ba36cb26d6a3d345c59020f756559953c

Note that the highlight background should also be re-done — I like the versions in the original design and on joplinapp.org and joplinhub.com better.

**Comment by personalizedrefrigerator** [comment]
Closing as completed in 1e10b62.
