### ISSUE TITLE
Use the crown icon to represent the Recommended plugin

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#12]
In the app we use a crown icon so we should use the same here.

Is it possible to put it in the top right corner too, next to the description?

<img width="333" alt="image" src="https://github.com/joplin/website-plugin-discovery/assets/1285584/89854ddd-57d5-498a-b83c-20f6dee54247">

**Comment by personalizedrefrigerator** [comment]
Partially addressed by 1a7fad83101fa66b1a47d48a741f956b6cbebdc6:
![screenshot: Most popular category. Each recommended plugin in this section has a crown icon to the right of the title](https://github.com/joplin/website-plugin-discovery/assets/46334387/66c36200-3f6e-436a-9c9c-adba914367ab)

At present, however, the badge on the plugin details page is still a badge:
![screenshot: Rich markdown plugin details has crown recommended with a background below its title](https://github.com/joplin/website-plugin-discovery/assets/46334387/1c35949c-493b-485e-b0e1-f4306f0ccec7)
![screenshot: Similar to above, but with smaller screen so the other icons/buttons are adjusted in position](https://github.com/joplin/website-plugin-discovery/assets/46334387/0329daf1-e654-425e-a0f2-f918f5996263)

**Comment by personalizedrefrigerator** [comment]
Closing as completed (see above comment).
