### ISSUE TITLE
Make the social network icons more discreet

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#13]
I think just having the icons, without the names, and without a badge (like on joplinapp.org) would be enough

<img width="490" alt="image" src="https://github.com/joplin/website-plugin-discovery/assets/1285584/0a151f20-c342-40f2-a1d0-b8cf839aa8b4">

**Comment by personalizedrefrigerator** [comment]
Addressed in 7417a329e50c6356bc63cf772aec0010dde13957 and 1bd52d136e34e5d578338ede4ce1bcee7033d23c
