### ISSUE TITLE
Load the images by default in the plugin pages

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#15]
This is a nice touch and it shows consideration for the users, but on the other hand I feel it's an extra step that not everyone will want to deal with.

Also does it really load tracking cookies? The server may indeed log the request but those who have a problem with this use a vpn anyway.

Perhaps long term we could load the images via `objects.joplinusercontent.com` (but don't do it now because I don't know if the server would support the load), but for now I feel it would be better to just always load the images.

<img width="660" alt="image" src="https://github.com/joplin/website-plugin-discovery/assets/1285584/a45e45c4-52e8-481c-b57f-102681c422ef">

**Comment by personalizedrefrigerator** [comment]
Currently, images served via `raw.githubusercontent.com` are allowed (without requiring confirmation) as that site doesn't seem to load tracking cookies. If images are specified using relative paths in a README (and the plugin has a GitHub repository), the paths are automatically re-written to point to `raw.githubusercontent.com/user/repository/HEAD/path/to/image`.

As such, the warning is only shown for some images.

> Also does it really load tracking cookies?

It seems to — searching for an image on Bing, copying the image link (e.g. `https://th.bing.com/th/id/OIP.haHPwwitytLb0lKDme9w7AHaHa?w=160&h=180&c=7&r=0&o=5&pid=1.7`) and pasting the link into another site causes Chrome to list Bing as a site that loads cookies:

![screenshot: Bing loads cookies](https://github.com/joplin/website-plugin-discovery/assets/46334387/08bcf6eb-7545-42ac-a883-b9e549368f68)

**Comment by laurent22** [comment]
Thanks for checking, but I would prefer if we display the images by default. I feel handling cookies is a feature of the browser - the user already has the option to block third-party cookies or even all cookies, as well as install extensions to filter what should be allowed or not

**Comment by personalizedrefrigerator** [comment]
Fixed in 62ac9e540f34507e51f6cf3d8d1cff19bbb5066b
