### ISSUE TITLE
Make the search bar clear button click target bigger

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#16]
It's a bit difficult to click on. Also to make it clearer, please use a finger pointer when the mouse is over the button

<img width="93" alt="image" src="https://github.com/joplin/website-plugin-discovery/assets/1285584/da1fbe2b-f518-4c06-b1e0-7b78f38d343c">

**Comment by personalizedrefrigerator** [comment]
I think that the clear button is provided by your browser. On Firefox on Linux, there's no clear button:
![Screenshot: Input without clear button](https://github.com/joplin/website-plugin-discovery/assets/46334387/9ff689fa-edb0-4812-8445-7b0d76013bc8)

It should be styleable [with the `::-webkit-search-cancel-button` selector](https://developer.mozilla.org/en-US/docs/web/css/::-webkit-search-cancel-button).

As this is the default button provided by the web-browser, we have some options:
1. Create a custom "clear" button that is shown on all browsers.
2. Restyle the clear button on just the browsers that have one.

**Comment by laurent22** [comment]
I see, I guess it's because it has "type=search" so this clear button is added on macOS. In that case, let's leave it as it is
