### ISSUE TITLE
Display the date as "Oct 7 2023"

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#17]
And please remove the time:

<img width="461" alt="image" src="https://github.com/joplin/website-plugin-discovery/assets/1285584/4ab8cba8-69a2-4635-b711-2a8f2e6e16e1">

**Comment by personalizedrefrigerator** [comment]
87ea4d8d5d442c5faca3728781f2a55b52548d19 should fix this. It uses `Date.toLocaleString` with options to show a short month and numeric year/day.

On my computer, this localizes to

![May 8, 2022](https://github.com/joplin/website-plugin-discovery/assets/46334387/60ee7238-91fd-4607-ac70-26fe4cadf177)
