### ISSUE TITLE
Align "Install plugin" button with the plugin title

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#19]
The "Install plugin" button is floating a bit on its own, I think it would be better if it was aligned with the title (so aligned top)

<img width="1061" alt="image" src="https://github.com/joplin/website-plugin-discovery/assets/1285584/6262cf21-ade3-43d7-9b2c-8b674524cbbe">

**Comment by personalizedrefrigerator** [comment]
Addressed in be613e0279a173604c8d93758f9c667371325685
