### ISSUE TITLE
Remove the "About" text in the plugin page

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#21]
It doesn't seem necessary on most pages I checked since the README will have its own title

<img width="232" alt="image" src="https://github.com/joplin/website-plugin-discovery/assets/1285584/3935c956-3d8e-4980-8785-81ca7f482178">

**Comment by personalizedrefrigerator** [comment]
Fixed in 1b3c9d22a01b2f4ba86ac4833ca4d052e28d82a6
