### ISSUE TITLE
Update the default size to use smaller fonts and improve spacing in plugin pages

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#22]
Please update the style in the plugin pages. I suggest copying the style from Discourse for example (in light theme): https://discourse.joplinapp.org/t/importing-notes-from-other-notebook-applications/22425

The current font size is too big, in particular for headers, so please check the following:

- For font sizes, for regular text and H1, H2, etc. as well as spacing between paragraphs. 
- Also please check the line height.
- And also block codes
- And bullet points

I guess the blue link colour is fine, especially since it's similar to the logo

**Comment by personalizedrefrigerator** [comment]
This shouldn't necessarily be closed yet. It should be mostly addressed, but it's likely some further changes need to be made.

**Note**: It seems that GitHub is automatically closing issues mentioned in commit messages.

**Comment by personalizedrefrigerator** [comment]
I think this has been addressed.
