### ISSUE TITLE
Move nav bar below the logo in plugin pages

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#23]
In plugin pages, the nav bar is moved completely to the left. Instead it should be below the logo, like in the front page.

<img width="799" alt="image" src="https://github.com/joplin/website-plugin-discovery/assets/1285584/dcaf1e67-8bb0-4f24-88f6-f214b76b71ca">

**Comment by personalizedrefrigerator** [comment]
This was a regression and should be fixed by 929ba29cd3b76d52ecd5e2e338554e728da81adc.
