### ISSUE TITLE
unify the blue element everywhere (especially on link and navbars) to :  `#0455B8`

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#24]

**Comment by personalizedrefrigerator** [comment]
See https://github.com/joplin/website-plugin-discovery/commit/a26139e52d3a0bc8d2d726fcde3d0d6a46f73ec2, https://github.com/joplin/website-plugin-discovery/commit/d6171ace67ca476cf33a52c51b0a8ce259d7b8f5
