### ISSUE TITLE
Some images are not loaded

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#25]
For example on the Rich Markdown plugin:

<img width="354" alt="image" src="https://github.com/joplin/website-plugin-discovery/assets/1285584/53b1e3bd-549a-40e3-bb5d-5c14440c907a">

**Comment by personalizedrefrigerator** [comment]
Fixed in 231b8e3f79d79f550c041a1c45d3cb6f53e9ac2a by re-writing `https://github.com/[[org]]/[[project]]/blob/[[branch]]/path/to/image`-style links to `https://raw.githubusercontent.com/[[org]]/[[project]]/[[branch]]/path/to/image`-style links.
