### ISSUE TITLE
Change font of card titles to 1em

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#26]
<img width="292" alt="image" src="https://github.com/joplin/website-plugin-discovery/assets/1285584/e4a38030-cdbd-4f97-ae2e-efafdc9e76eb">

**Comment by personalizedrefrigerator** [comment]
See https://github.com/joplin/website-plugin-discovery/commit/257d7fc506a35d74267b7e8a430b126f057da86d
