### ISSUE TITLE
Switching from a category with few plugins to one with many makes the scrollbar appears and make the page move

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#28]
For example when switching from Themes to Productivity

Maybe the scrollbar should always be displayed, but disabled if there's no content? That will prevent the layout from moving left and right.

**Comment by personalizedrefrigerator** [comment]
> Maybe the scrollbar should always be displayed, but disabled if there's no content? That will prevent the layout from moving left and right.

Done in https://github.com/joplin/website-plugin-discovery/commit/3af305d3aa0c812bab09168c6459cdf74877756f
