### ISSUE TITLE
Update selected state of sidebar

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#29]
Please make it look like so:

![image](https://github.com/joplin/website-plugin-discovery/assets/1285584/f29ec72a-4073-4410-9872-a53a80e81286)

For the hover effect, I suggest doing the same but with a lower opacity

**Comment by personalizedrefrigerator** [comment]
Addressed in c6efcc53d1321944dd9ba5fdaf6243fcb0b1d10e
