### ISSUE TITLE
Change the card background colour

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#30]
From Marta:

> Here, I change the background color for gray fields to brighter #fafafa and in a variable *bs-border-color-translucent* I changed the alpha value to: bs-border-color-translucent:rgba(0,0,0,0.1); Here what it looks like after the changes:

![image](https://github.com/joplin/website-plugin-discovery/assets/1285584/92af103d-ea42-40cd-a62d-b3662ab5c6e6)

**Comment by personalizedrefrigerator** [comment]
Completed in https://github.com/joplin/website-plugin-discovery/commit/ab20a23bc65ec28b874d04240c31603d8e184059
