### ISSUE TITLE
Add privacy policy link

### ISSUE THREAD

**Issue by personalizedrefrigerator** [joplin/website-plugin-discovery#32]
A privacy policy link should be added to the sidebar, like in the Figma design:
![screenshot: Privacy policy link in left sidebar](https://github.com/joplin/website-plugin-discovery/assets/46334387/7deefd5e-80da-42b7-9eaf-7f7c7d905498)

**Comment by laurent22** [comment]
We need a privacy policy link but I think it should be in the footer. Is that from the latest Figma design?

**Comment by personalizedrefrigerator** [comment]
Mostly completed in https://github.com/joplin/website-plugin-discovery/commit/c25d6e02e8c7d4aa1e92db5f70557b21c1d4878b (privacy policy placeholder needs to be replaced).

**Comment by laurent22** [comment]
Please use the following document:

```
# Joplin Plugins Privacy Policy

## Who are we?

The Joplin Plugins website is owned by Joplin, registered at 3 Place Simone Veil, CS 20739 54064 Nancy, France. SIREN: RCS Nancy 919 395 087

## What information do we collect?

We do not collect any information.

## Plugin sub-pages

Plugin authors can choose to include external images in a plugin's subpage of this website, which may allow third parties to access your IP or certain cookies depending on your browser settings.
```

This privacy policy only applies to the website, so for now we won't put a section about the plugins themselves. Maybe we should eventually have a privacy policy that covers all apps, website and plugins, with different sections, so that there's a central place to get all the information.

**Comment by personalizedrefrigerator** [comment]
Closing as completed: The privacy policy link is present in the footer:

![screenshot: Privacy policy link present in footer.](https://github.com/joplin/website-plugin-discovery/assets/46334387/d2dddd3d-a9ab-41c7-9dce-5522c32557d1)
