### ISSUE TITLE
Support screenshots and icons from non-GitHub repositories

### ISSUE THREAD

**Issue by personalizedrefrigerator** [joplin/website-plugin-discovery#35]
# Summary

At present, the plugin website only displays screenshots from plugins that have an associated GitHub repository.

Internally, this is done by converting screenshot paths to `raw.githubusercontent.com` URLs. For example, 
```
https://raw.githubusercontent.com/personalizedrefrigerator/joplin-plugin-revealjs-slides/HEAD/images/screenshot-dark.png
```

# Proposed solutions

1. Add similar logic for other common repository hosting services
2. Publish screenshots and icons to NPM.
    - Screenshots and icons could then be served with the plugin website
    - The build script should currently fail if screenshots are over 1 MiB.
3. Allow users to specify URLs to the icons in the plugin manifest.

**Comment by laurent22** [comment]
For now please only support screenshots hosted on GitHub and absolute urls. We'll see if the rest is needed depending on user feedback

**Comment by personalizedrefrigerator** [comment]
https://github.com/laurent22/joplin/pull/9254 adds support for URLs to the default template. Previously, URLs did not work with the build script.

**Comment by personalizedrefrigerator** [comment]
https://github.com/joplin/website-plugin-discovery/commit/413c3d952e1d3b0e6a28af45b21361ee45269e38 adds support for rendering screenshots specified with URLs in their manifests.
