### ISSUE TITLE
use subdomain instead of the default one

### ISSUE THREAD

**Issue by Wladefant** [joplin/website-plugin-discovery#37]
Personalizedrefridgetor I like the changes very much. 

I would suggest changing to a subdomain of the joplin website like plugins.joplinapp.org or joplinapp.org/plugins

**Comment by personalizedrefrigerator** [comment]
Related
- https://github.com/laurent22/joplin/pull/9471
- https://github.com/laurent22/joplin/pull/9469

**Comment by laurent22** [comment]
We have now moved the website to /plugins
