### ISSUE TITLE
Add a link to go back to joplinapp.org

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#39]
Not sure where it should go and how it should look, but there should be a way to go back to joplinapp.org

**Comment by personalizedrefrigerator** [comment]
Here are some options:
- At the bottom of the screen, as one of the "social" icons.
- At the top of the screen, instead of the "Popular"/"Recommended"/"All plugins"
- At the top of the screen, when clicking on the logo.

**Comment by laurent22** [comment]
> At the top of the screen, when clicking on the logo.

Yes maybe we should change the "Joplin plugins" logo to the regular "Joplin" logo, and add the plugin info like it's done for Obsidian or Notion?

https://obsidian.md/plugins

https://www.notion.so/integrations/all

That would make the plugin repository better integrated to the main website

**Comment by personalizedrefrigerator** [comment]
![image](https://github.com/joplin/website-plugin-discovery/assets/46334387/d9d4480f-95c1-4d58-b04d-67c01eb62e94)
