### ISSUE TITLE
Improve padding of heading

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#41]
There are three different margins at the top at the moment - One for the Joplin logo, another for the Home button and another for the content margin. And that padding is different from the main page (the Home button jumps when changing from a plugin page to the home page).

I think we should do this:

- The Home link should be right below the "Joplin" logo
- And it shouldn't move when switching from a plugin page to the home page
- The "Install plugin" button should be right-aligned with the Search box
- The plugin preview image (currently on the left of the plugin title) should be removed. It should only be used on the home page
- And see below for the other changes:

## Current
 
<img width="588" alt="image" src="https://github.com/joplin/website-plugin-discovery/assets/1285584/ab13b1b6-15a1-4d7f-9c3d-418854eb5a54">

## Changes

<img width="763" alt="image" src="https://github.com/joplin/website-plugin-discovery/assets/1285584/f2171780-c787-4bb4-9837-0c84cb0bc50e">

**Comment by personalizedrefrigerator** [comment]
This has been partially addressed &mdash; alignment should be improved, but the position of the icon still needs to be updated.

**Comment by personalizedrefrigerator** [comment]
Updated UI:
![screenshot: Much smaller icon is just to the left of the title](https://github.com/joplin/website-plugin-discovery/assets/46334387/57cf86b1-1121-45d5-9e62-a906afde094f)
![screenshot: Plugin with no icon shows just the title](https://github.com/joplin/website-plugin-discovery/assets/46334387/cecec9c4-bc64-4dbd-8377-25be03fa539b)
