### ISSUE TITLE
Miner bug in recommended section

### ISSUE THREAD

**Issue by zahidhussain998** [joplin/website-plugin-discovery#45]
I just found the miner bug in recommended section 

![s](https://github.com/joplin/website-plugin-discovery/assets/100913055/cf6bbf0a-671f-45f7-9573-81c183800b01)

**Comment by zahidhussain998** [comment]
please assign me this issue so that I can start working on this issue thanks

**Comment by personalizedrefrigerator** [comment]
> I just found the miner bug in recommended section

Please provide a bit more information — is the bug the size of the highlight? (It could also be the position of the "popularity" dropdown).

> please assign me this issue so that I can start working on this issue thanks

We generally don't assign issues. Feel free to work on this without being assigned.

Thank you for reporting this issue!

**Comment by zahidhussain998** [comment]
Thanks for looking into the issue. The bug seems to be related to the "Recommended plugins" dropdown, and it's roughly the size of the highlighted area. I'll start working on fixing this.

**Comment by roman-r-m** [comment]
From the email notification I got, I thought it was something about a crypto miner.

**Comment by zahidhussain998** [comment]
@personalizedrefrigerator I just raised the new PR please check
